# Generated by Django 5.0.3 on 2024-03-27 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_customuser_phone_no_customuser_roll_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='roll_no',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_type',
        ),
    ]
